package m4.Team2;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;

class LeadsPage extends javax.swing.JFrame {

    private static int DEFAULT_ROW_HEIGHT = 40;
    private static String DEFAULT_BUTTON_LABEL = "Respond";

    private String dealerId;
    private JTable jTable_Leads;


    /**
     * Creates new form LeadsPage
     */

    public LeadsPage(String dealerId) {
        this.dealerId = dealerId;
        initComponents();
        displayTable();
    }

    private ArrayList<Lead> leadList(){
        ArrayList<Lead> leadList = new ArrayList<>();
        Connection conn;
        try {
            //STEP 2: Register JDBC driver
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://is-swang01.ischool.uw.edu:1433;"
                    + "databaseName= VechileManagementSystem;user=INFO6210;password=NEUHusky!";
            //STEP 3: Open a connection
            conn = DriverManager.getConnection(connectionUrl);
            //STEP 4: Execute a query

            String query = "SELECT leadId, firstName, lastName, vehicleId, email, contactNo, comment, dealerComment, dealerId FROM dbo.CustomerRequest WHERE dealerID = '" + this.dealerId + "'";

            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(query);

            while(rs.next())
            {
                Lead lead = new Lead();
                lead.setFirstName(rs.getString("firstName"));
                lead.setLastName(rs.getString("lastName"));
                lead.setVehicleId(rs.getString("vehicleId"));
                lead.setEmail(rs.getString("email"));
                lead.setContactNo(rs.getString("contactNo"));
                lead.setLeadId(rs.getString("leadId"));
                lead.setComment(rs.getString("comment"));
                lead.setDealerId(rs.getString("dealerId"));
                lead.setDealerComment(rs.getString("dealerComment"));

                leadList.add(lead);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return leadList;
    }

    private void displayTable(){
        DefaultTableModel model = (DefaultTableModel)jTable_Leads.getModel();
        Object[] column = new Object[4];
        ArrayList<Lead> list = leadList();
        for (int i = 0; i < list.size(); i++) {
            column[0] = i + 1;
            column[1] = list.get(i).getFirstName();
            column[2] = list.get(i).getVehicleId();
            model.addRow(column);
        }
        TableButtonRenderer table = new TableButtonRenderer();
        table.setText(DEFAULT_BUTTON_LABEL);
        jTable_Leads.getColumnModel().getColumn(3).setCellRenderer(table);
        jTable_Leads.getColumnModel().getColumn(3).setCellEditor(new TableButtonEditor(list, new JCheckBox(), DEFAULT_BUTTON_LABEL));
        jTable_Leads.setPreferredScrollableViewportSize(jTable_Leads.getPreferredSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        JPanel leadLabelPanel = new JPanel();
        JLabel leadsLabel = new JLabel();
        JPanel tablePanel = new JPanel();
        JScrollPane jScrollPane1 = new JScrollPane();
        jTable_Leads = new JTable() {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return colIndex == 3;
            }
        };

        jTable_Leads.setModel(
            new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                new String [] {
                    "Number", "Customer Name", "Car Model", "Respond"
                }
            )
        );
        jTable_Leads.setRowHeight(DEFAULT_ROW_HEIGHT);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        leadsLabel.setFont(new java.awt.Font("Times New Roman", Font.BOLD | Font.ITALIC, 24)); // NOI18N
        leadsLabel.setText("Leads");

        javax.swing.GroupLayout leadLabelPanelLayout = new javax.swing.GroupLayout(leadLabelPanel);
        leadLabelPanel.setLayout(leadLabelPanelLayout);
        leadLabelPanelLayout.setHorizontalGroup(
            leadLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(leadLabelPanelLayout.createSequentialGroup()
                    .addGap(276, 276, 276)
                    .addComponent(leadsLabel)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leadLabelPanelLayout.setVerticalGroup(
            leadLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(leadLabelPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(leadsLabel)
                    .addContainerGap(73, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jTable_Leads);

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(leadLabelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(leadLabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }

}
